'use client'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ContextProvider from "./context/ContextProvider";
import { Layout, Switch } from "antd";
import { useState } from "react";
import { MoonOutlined, SunOutlined } from "@ant-design/icons";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const {Content, Header, Footer} = Layout
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [darkTheme, setDarkTheme] = useState(false)
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-[100%] bg-[#f5f5f5]`}
      >
        <Layout className={"flex h-[100vh] dark:bg-[#1c1c1c] " + (darkTheme && 'dark')}>
          <Header className=" bg-blue-700 flex justify-center items-center min-h-24 mb-9 dark:bg-black">

            <h1 className="mt-2 flex text-4xl font-semibold text-gray-50 dark:text-indigo-400 w-full justify-center">
              ToDo
            </h1>
            <div>
            <Switch checkedChildren={<SunOutlined />} className="bg-blue-500 dark:bg-indigo-700" unCheckedChildren={<MoonOutlined />} onChange={()=>{setDarkTheme(!darkTheme)}}/>
            </div>
            </Header>
          <Content className="h-full">
            <ContextProvider>
            <div className="md:flex md:justify-center">
              {children}
            </div>
            </ContextProvider>
          </Content>
        
        </Layout>
      </body>
    </html>
  );
}
